name: polarimetric_imaging
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - nvidia::cudatoolkit=11.7
  - pytorch
  - torchvision
  - pytorch-cuda=11.7
  - opencv=4.7.0
  - numpy
  - matplotlib
  - pandas
  - tqdm
  - pip
  - pip:
    - arena-api/arena_api-2.3.3-py3-none-any.whl